"""
ARIS-Idea: LangGraph Graph Definition
Wires all 11 nodes + report generation into a stateful, cyclic agent workflow.
"""

from __future__ import annotations

import logging
from datetime import datetime

from langgraph.graph import StateGraph, START, END

from state import ARISState
from nodes.query_expansion import query_expansion_node
from nodes.data_retrieval import data_retrieval_node
from nodes.knowledge_extraction import knowledge_extraction_node
from nodes.limitation_embedding import limitation_embedding_node
from nodes.gap_clustering import gap_clustering_node
from nodes.gap_validation import gap_validation_node
from nodes.idea_generation import idea_generation_node
from nodes.idea_embedding import idea_embedding_node
from nodes.novelty_evaluation import novelty_evaluation_node
from nodes.critic_loop import critic_loop_node, critic_router
from nodes.evaluation_metrics import evaluation_metrics_node
from utils.gemini_client import reset_call_counters
from utils.semantic_scholar import reset_s2_state

logger = logging.getLogger(__name__)


# ─── Pipeline Init (resets all counters/caches) ───────────────────────────────

def init_pipeline_node(state: ARISState) -> dict:
    """Reset all API call counters and caches at the start of each run."""
    reset_call_counters()
    reset_s2_state()
    logger.info("Pipeline initialized — call counters and caches reset")
    return {"status_message": "✅ Pipeline initialized"}


# ─── Report Generation (final node) ──────────────────────────────────────────

def report_generation_node(state: ARISState) -> dict:
    """Compile state into a Markdown report."""
    topic = state.get("user_topic", "Unknown Topic")
    papers = state.get("retrieved_papers", [])
    knowledge = state.get("extracted_knowledge", [])
    clusters = state.get("limitation_clusters", [])
    gaps = state.get("validated_gaps", [])
    ideas = state.get("generated_ideas", [])
    scores = state.get("novelty_scores", [])
    metrics = state.get("evaluation_metrics", {})
    iteration = state.get("iteration_count", 0)

    report = f"""# ARIS Research Report
## Topic: {topic}
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Papers Analyzed**: {len(papers)} | **Gaps Found**: {len(gaps)} | **Ideas Generated**: {len(ideas)} | **Iterations**: {iteration}

---

## 📚 Research Landscape Summary

Analyzed **{len(papers)}** peer-reviewed papers from Semantic Scholar, focusing on limitations, bottlenecks, and open challenges in **{topic}**.

### Top Papers by Citation Count

| # | Title | Year | Citations |
|---|-------|------|-----------|
"""
    for i, p in enumerate(papers[:10], 1):
        report += f"| {i} | {p.get('title', 'N/A')} | {p.get('year', '?')} | {p.get('citationCount', 0):,} |\n"

    report += f"""
---

## 🔍 Limitation Clusters

Found **{len(clusters)}** clusters of recurring limitations:

"""
    for c in clusters[:5]:
        report += f"### Cluster {c['cluster_id']} (Density: {c['density']:.2f}, Size: {c['size']})\n"
        for lim in c.get("representative_limitations", [])[:3]:
            report += f"- {lim}\n"
        report += "\n"

    report += "---\n\n## 🎯 Validated Research Gaps\n\n"
    for i, gap in enumerate(gaps, 1):
        report += f"**Gap {i}:** {gap}\n\n"

    report += "---\n\n## 💡 Verified Project Blueprints\n\n"
    for i, idea in enumerate(ideas):
        score_data = scores[i] if i < len(scores) else {}
        novelty = score_data.get("final_score", 0)
        passed = "✅" if score_data.get("passed", False) else "⚠️"

        report += f"""### {passed} Idea {i+1}: {idea.get('title', 'Untitled')}
- **Approach**: {idea.get('approach_type', 'N/A')}
- **Target Gap**: {idea.get('target_gap', 'N/A')}
- **Novelty Score**: {novelty:.2f}
- **Motivation**: {idea.get('motivation', 'N/A')}
- **Methodology**: {idea.get('methodology', 'N/A')}
- **Expected Impact**: {idea.get('expected_impact', 'N/A')}
- **Supporting Citations**: {', '.join(idea.get('supporting_citations', []))}

"""

    report += f"""---

## 📊 Evaluation Metrics

| Metric | Value |
|--------|-------|
| Average Novelty Score | {metrics.get('average_novelty_score', 0):.3f} |
| Pass Rate | {metrics.get('pass_rate', 0):.1%} |
| Gap Coverage | {metrics.get('gap_coverage', 0):.1%} |
| Iterations Used | {metrics.get('iterations_used', 0)} |
| Constraints Generated | {metrics.get('constraints_generated', 0)} |

---

## 🛠️ Methodology

This report was generated by **ARIS-Idea** (Autonomous Research & Idea Generation System), a multi-agent AI pipeline:

1. **Query Expansion** — Gemini 2.0 Flash converted the topic into targeted search queries
2. **Data Retrieval** — Semantic Scholar API fetched top-cited papers
3. **Knowledge Extraction** — Gemini 2.0 Flash extracted structured limitations
4. **Limitation Embedding** — text-embedding-004 vectorized all limitations
5. **Gap Clustering** — K-Means clustering identified recurring limitation patterns
6. **Gap Validation** — Gemini 2.0 Pro validated gaps using cluster density evidence
7. **Idea Generation** — Gemini 2.0 Pro proposed novel research ideas
8. **Novelty Verification** — Multi-component scoring (semantic + structural + keyword)
9. **Critic-in-the-Loop** — Adaptive constraints for self-correction
10. **Evaluation Metrics** — Pipeline quality assessment
"""

    return {
        "final_report": report,
        "status_message": "✅ Report generated successfully!",
    }


# ─── Build & Compile Graph ───────────────────────────────────────────────────

def build_graph() -> StateGraph:
    """Build and compile the ARIS-Idea LangGraph pipeline."""
    builder = StateGraph(ARISState)

    # Register all nodes (init_pipeline resets counters/caches)
    builder.add_node("init_pipeline", init_pipeline_node)
    builder.add_node("query_expansion", query_expansion_node)
    builder.add_node("data_retrieval", data_retrieval_node)
    builder.add_node("knowledge_extraction", knowledge_extraction_node)
    builder.add_node("limitation_embedding", limitation_embedding_node)
    builder.add_node("gap_clustering", gap_clustering_node)
    builder.add_node("gap_validation", gap_validation_node)
    builder.add_node("idea_generation", idea_generation_node)
    builder.add_node("idea_embedding", idea_embedding_node)
    builder.add_node("novelty_evaluation", novelty_evaluation_node)
    builder.add_node("critic_loop", critic_loop_node)
    builder.add_node("evaluation_metrics", evaluation_metrics_node)
    builder.add_node("report_generation", report_generation_node)

    # Linear edges
    builder.add_edge(START, "init_pipeline")
    builder.add_edge("init_pipeline", "query_expansion")
    builder.add_edge("query_expansion", "data_retrieval")
    builder.add_edge("data_retrieval", "knowledge_extraction")
    builder.add_edge("knowledge_extraction", "limitation_embedding")
    builder.add_edge("limitation_embedding", "gap_clustering")
    builder.add_edge("gap_clustering", "gap_validation")
    builder.add_edge("gap_validation", "idea_generation")
    builder.add_edge("idea_generation", "idea_embedding")
    builder.add_edge("idea_embedding", "novelty_evaluation")
    builder.add_edge("novelty_evaluation", "critic_loop")

    # Conditional edge: Critic loop decision gate
    builder.add_conditional_edges(
        "critic_loop",
        critic_router,
        {
            "pass": "evaluation_metrics",
            "retry": "idea_generation",
            "force_pass": "evaluation_metrics",
        },
    )

    # Final edges
    builder.add_edge("evaluation_metrics", "report_generation")
    builder.add_edge("report_generation", END)

    return builder.compile()

